[project]
name = "gif-color-changer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.4",
    "pillow>=12.2.0",
]

[project.scripts]
gifcc = "gif_color_changer.cli:main"

[build-system]
requires = ["uv_build>=0.11.6,<0.12"]
build-backend = "uv_build"
